global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:

  - job_name: machines
    static_configs: 
      - targets: 
        - '192.168.108.128:9090'
        - '192.168.108.128:3000'
        - '192.168.108.128:68'
        - '10.0.0.4:9100'
        - '10.0.0.7:9100'
        - '10.0.0.1:9100'
        - '192.168.108.1:9100'
        - '87.89.214.120:9100'


  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']